language: go
sudo: false
dist: trusty
osx_image: xcode8.3
go: 1.8.x

os:
- linux
- osx

cache:
  directories:
  - node_modules

before_script:
- if [[ $(uname) == Darwin ]]; then
    sudo pip2 install flake8;
  else
    pip install --user flake8;
  fi
- mkdir -p ${GOPATH%%:*}/src/gopkg.in/urfave
- rm -rvf ${GOPATH%%:*}/src/marwan.io/cli
- rm -rvf ${GOPATH%%:*}/pkg/*/marwan.io/cli.a
- ln -sv ${TRAVIS_BUILD_DIR} ${GOPATH%%:*}/src/marwan.io/cli

script:
- flake8 runtests cli-v1-to-v2 generate-flag-types
- make all
